server:
 port: 8080

spring:
 datasource:
   username: "root"
   password: "935117256A1B2C3D4_"
   url: jdbc:mysql://localhost:3306/search_engine?autoReconnect=true&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
   hibernate:
     ddl-auto: update
   show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru